'use strict';
(()=>{
const $=id=>document.getElementById(id),admin=location.pathname==='/payout-review';
const API=admin?'':(window.API_BASE||'https://api.darrius.ai').replace(/\/$/,'');
let lang=(new URLSearchParams(location.search).get('lang')||'zh').startsWith('zh')?'zh':'en',busy=false,profile={version:0},rows=[],cursor=null,nextCursor=null,previousCursors=[];
const t=(zh,en)=>lang==='zh'?zh:en,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states=s=>({NOT_SUBMITTED:t('尚未提交','Not submitted'),PENDING:t('待财务审核','Pending finance review'),APPROVED:t('资料审核通过','Details approved'),CHANGES_REQUESTED:t('需要修改','Changes requested')}[s]||s);
function error(code){return ({payout_not_configured:t('收款资料服务尚未配置。','Payout details are not configured.'),authentication_required:t('请先返回推荐人中心登录。','Sign in through the referral center first.'),permission_denied:t('需要财务管理权限。','Finance permission is required.'),profile_changed:t('资料已更新，请刷新后重试。','Details changed. Refresh and retry.'),account_mismatch:t('两次输入的账号不一致。','Account numbers do not match.'),invalid_routing_number:t('请检查美国 Routing Number，应为有效的9位数字。','Check the 9-digit US routing number.'),invalid_swift:t('请检查8位或11位 SWIFT/BIC。','Check the 8- or 11-character SWIFT/BIC.'),invalid_pdf:t('请上传不含脚本或附件、未加密、2MB以内的PDF。','Upload an unencrypted PDF under 2MB without scripts or attachments.'),tax_pdf_required:t('请上传填写并签署后的税务表格。','Upload your completed and signed tax form.'),application_required:t('请先提交推荐人申请。','Submit an affiliate application first.'),reason_required:t('请填写至少3个字符的审核或查看理由。','Enter a review/access reason of at least 3 characters.')})[code]||t('操作未完成，请检查必填信息后重试。','Could not complete the request. Check required fields and retry.');}
async function api(path,body,blob=false){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const r=await fetch(API+path,{credentials:'include',cache:'no-store',signal:controller.signal,...(body?{method:'POST',headers:{'Content-Type':'application/json',...(admin?{'X-Finance-Request':'1'}:{})},body:JSON.stringify(body)}:{})});if(!r.ok){let d={};try{d=await r.json();}catch(_){}throw Error(error(d.error));}return blob?r.blob():r.json();}finally{clearTimeout(timer);}}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);$('message').textContent='';try{await fn();}catch(e){$('message').textContent=e.name==='AbortError'||e instanceof TypeError?t('网络连接失败，请重试。','Connection failed. Retry.'):e.message;}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
let pendingDownload = null;
function clearDownload(){
 if(!pendingDownload)return;
 clearTimeout(pendingDownload.timer);
 URL.revokeObjectURL(pendingDownload.url);
 pendingDownload.panel.remove();
 pendingDownload=null;
}
function download(blob,name){
 clearDownload();
 const url=URL.createObjectURL(blob),panel=document.createElement('section');
 panel.className='card';panel.setAttribute('aria-label',t('文件下载','File download'));
 const info=document.createElement('p'),link=document.createElement('a');
 info.textContent=t('文件已准备好。如果下载未自动开始，请点击下方链接；链接在一分钟后失效，可重新获取。','Your file is ready. If the download did not start, use the link below. It expires in one minute; request the file again if needed.');
 link.href=url;link.download=name;link.textContent=t('点击保存：','Save file: ')+name;
 panel.append(info,link);$('message').after(panel);
 pendingDownload={url,panel,timer:setTimeout(clearDownload,60000)};
 link.click();
 panel.scrollIntoView({block:'nearest',behavior:'smooth'});
}
window.addEventListener('pagehide',clearDownload);
function render(){clearDownload();document.documentElement.lang=lang==='zh'?'zh-CN':'en';$('language').textContent=t('🌐 English','🌐 中文');$('back').textContent=admin?t('返回财务后台','Back to finance'):t('返回推荐人中心','Back to referral center');$('back').href=(admin?'/':'referral-account.html')+'?lang='+lang;$('title').textContent=admin?t('收款资料审核','Payout details review'):t('银行收款与税务资料','Bank and tax details');$('intro').textContent=t('用于推荐佣金结算。提交资料不会发起转账；更新资料后需要重新审核。','For referral commission settlement. Submitting details does not transfer money. Changes require a new review.');admin?renderAdmin():renderAccount();}
function renderAccount(){const fields=[['beneficiary',t('收款人／公司法定名称','Beneficiary / legal entity name'),160],['beneficiary_address',t('收款人完整地址','Beneficiary full address'),500],['account_number',t('银行账号／IBAN','Account number / IBAN'),64],['account_confirmation',t('再次输入银行账号／IBAN','Confirm account number / IBAN'),64],['bank_name',t('收款银行名称','Bank name'),160],['bank_address',t('收款银行完整地址','Full bank address'),500],['bank_country',t('银行国家代码（如 US、CN、CA）','Bank country code (US, CN, CA)'),2],['routing_number',t('Routing Number（美国）','Routing number (US)'),9],['swift',t('SWIFT / BIC（非美国）','SWIFT / BIC (outside US)'),11]];
$('content').innerHTML=`<section class="card"><h2>${states(profile.status||'NOT_SUBMITTED')}</h2>${profile.account_last4?`<p>${esc(profile.bank_name)} · •••• ${esc(profile.account_last4)} · ${esc(profile.tax_form)}</p>`:''}<p>${esc(profile.note||'')}</p><button id="refresh">${t('刷新状态','Refresh status')}</button></section><form id="payoutForm" autocomplete="off"><h2>${t('提交／更新收款资料','Submit / update payout details')}</h2><p>${t('为保护账号，已保存的完整资料不会自动回填。修改时请重新填写全部银行资料。','Saved full details are not prefilled. Re-enter all bank details when updating.')}</p><div class="grid">${fields.map(([id,label,max])=>`<label id="label-${id}">${label}<input id="${id}" name="${id}" maxlength="${max}" required autocomplete="off" ${id.includes('account_')?'type="password"':''}></label>`).join('')}<label>${t('结算币种','Settlement currency')}<select name="currency"><option>USD</option></select></label><label>${t('税务表格类型','Tax form type')}<select id="tax_form" name="tax_form"><option value="W9">W-9</option><option value="W8BEN">W-8BEN</option><option value="W8BENE">W-8BEN-E</option></select></label><div class="wide"><p>${t('W-9：美国税务身份；W-8BEN：外国个人；W-8BEN-E：外国实体。请依据表格说明选择，银行国家不决定税务身份。其他适用情形请联系财务。','W-9: US tax status; W-8BEN: foreign individual; W-8BEN-E: foreign entity. Follow the form instructions; bank country does not determine tax status. Contact finance for other cases.')}</p><button type="button" id="template">${t('下载所选空白表格','Download selected blank form')}</button><label>${t('上传填写并签署的 PDF（最多2MB）','Upload completed and signed PDF (max 2MB)')}<input type="file" id="tax_pdf" accept="application/pdf"></label><p>${t('只有未更换表格类型时，才能保留已上传文件。上传不代表税务审核通过。','The previous upload is retained only if the form type is unchanged. Uploading does not mean tax approval.')}</p></div><label class="wide"><input type="checkbox" id="confirmed" required>${t('我确认资料准确，并授权用于我的推荐佣金结算。','I confirm the details are accurate and authorize their use for my referral commission settlement.')}</label></div><div class="actions"><button type="submit">${t('提交财务审核','Submit for finance review')}</button></div></form>`;
if(profile.tax_form)$('tax_form').value=profile.tax_form;
const country=()=>{const us=$('bank_country').value.toUpperCase()==='US';$('label-routing_number').hidden=!us;$('routing_number').required=us;$('label-swift').hidden=us;$('swift').required=!us;};$('bank_country').addEventListener('input',country);country();
$('refresh').onclick=()=>run(load);
$('template').onclick=()=>run(async()=>download(await api('/api/referral/account/tax-form/'+$('tax_form').value,undefined,true),$('tax_form').value+'.pdf'));
$('payoutForm').onsubmit=e=>{e.preventDefault();run(async()=>{const body=Object.fromEntries(new FormData(e.target));body.version=profile.version;body.confirmed=$('confirmed').checked;const f=$('tax_pdf').files[0];if(f){if(f.size>2*1024*1024)throw Error(error('invalid_pdf'));body.tax_pdf=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f);});}profile=await api('/api/referral/account/payout',body);render();$('message').textContent=t('资料已加密保存，等待财务审核。','Details saved encrypted. Awaiting finance review.');});};}
function renderAdmin(){$('content').innerHTML=`<button id="refresh">${t('刷新','Refresh')}</button><p>${t('仅显示已提交收款资料的推荐人；账号默认脱敏。资料审核不代表银行已验证，也不发起付款。','Only affiliates who submitted payout details appear. Accounts are masked. Review does not verify bank ownership or initiate payment.')}</p>`+rows.map((r,i)=>`<section class="card"><h2>${esc(r.user_id)} · ${states(r.status)}</h2><p>${esc(r.bank_name)} · •••• ${esc(r.account_last4)} · ${esc(r.tax_form)}</p><label>${t('查看／审核理由（不要填写账号或税号）','Access / review reason (no account or tax IDs)')}<textarea id="reason-${i}" maxlength="500"></textarea></label><div class="actions"><button data-action="reveal" data-i="${i}">${t('查看银行资料','View bank details')}</button><button data-action="document" data-i="${i}">${t('下载税务文件','Download tax document')}</button>${r.status==='PENDING'?`<button data-action="APPROVED" data-i="${i}">${t('审核通过','Approve')}</button><button data-action="CHANGES_REQUESTED" data-i="${i}">${t('退回修改','Request changes')}</button>`:''}</div><div id="detail-${i}"></div></section>`).join('');if(!rows.length)$('content').innerHTML+=`<section class="card">${t('暂无提交资料','No submissions yet')}</section>`;$('content').insertAdjacentHTML('beforeend',`<nav class="actions" aria-label="${t('分页','Pagination')}">${previousCursors.length?`<button id="previousPage">${t('上一页','Previous')}</button>`:''}${nextCursor?`<button id="nextPage">${t('下一页','Next')}</button>`:''}</nav>`);
$('refresh').onclick=()=>run(load);
if($('nextPage'))$('nextPage').onclick=()=>run(()=>load(nextCursor,'next'));
if($('previousPage'))$('previousPage').onclick=()=>run(()=>load(previousCursors[previousCursors.length-1],'previous'));
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>run(async()=>{const i=+b.dataset.i,r=rows[i],a=b.dataset.action,review=['APPROVED','CHANGES_REQUESTED'].includes(a);const body={version:r.version,reason:$('reason-'+i).value,...(review?{decision:a}:{})};const result=await api('/api/payouts/'+r.id+'/'+(review?'review':a),body,a==='document');if(a==='document')download(result,'tax-form.pdf');else if(a==='reveal'){const node=document.createElement('pre');node.textContent=Object.entries(result.details).filter(([k])=>!['review_note'].includes(k)).map(([k,v])=>k+': '+v).join('\n');$('detail-'+i).replaceChildren(node);setTimeout(()=>node.remove(),60000);}else await load();}));}
async function load(target=cursor,direction=null){if(admin){const result=await api('/api/payouts'+(target?'?before='+encodeURIComponent(target):''));if(direction==='next')previousCursors.push(cursor);if(direction==='previous')previousCursors.pop();cursor=target;rows=result.profiles;nextCursor=result.next_cursor;}else profile=await api('/api/referral/account/payout');render();}
$('language').onclick=()=>{const drafts=[...document.querySelectorAll('input:not([type=file]),select,textarea')].map(e=>[e.id,e.value,e.checked]);if(document.querySelector('input[type=file]')?.files.length){$('message').textContent=t('请先提交已选择的文件，再切换语言。','Submit the selected file before switching language.');return;}lang=lang==='zh'?'en':'zh';render();drafts.forEach(([id,value,checked])=>{if($(id)){$(id).value=value;$(id).checked=checked;}});$('bank_country')?.dispatchEvent(new Event('input'));};render();run(load);
})();
